// Generates the synthetic device fleet the agent works over.
//
// Synthetic on purpose: this repo goes public, so the telemetry has to be ours
// to publish. That trade has a cost worth naming. Real data has one virtue a
// generator cannot fake, which is that nobody chose the answer. Here I could
// quietly make the answer whatever I wanted, and a loop study whose finding was
// planted by the person running the study is worth nothing.
//
// So: the process below is stated in full, the seed is fixed, and the answer to
// the task question was read off the output afterwards rather than designed in.
// If the output turns out boring, the question changes, not the data.
//
// Eight fields. Every tool result is appended to the context and re-sent on the
// next model call, so the width of one row sets the floor on how fast context
// grows during a run.
//
// Run once. The output is committed, so the agent's world never changes
// underneath an experiment. A loop study is worthless if the data moves.

import { writeFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SEED = 20260808;

// Small seeded PRNG. Math.random() would make the fleet different on every run,
// which breaks the "world never changes" rule above.
function mulberry32(a) {
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const rand = mulberry32(SEED);
const randn = () => Math.sqrt(-2 * Math.log(1 - rand())) * Math.cos(2 * Math.PI * rand());
const pick = (xs) => xs[Math.floor(rand() * xs.length)];
const clamp = (x, lo, hi) => Math.min(hi, Math.max(lo, x));

const SITES = ['STM', 'NGH', 'WRC', 'LKV', 'BRD', 'CHC', 'EVN', 'PDM'];

// hours: [mu, sigma] of a lognormal, so utilisation is skewed the way a real
// fleet is: many lightly used devices, a long tail of workhorses.
// Firmware is listed oldest first; the oldest build carries a health penalty,
// which is the one structural signal deliberately built in.
const MODELS = [
  { model: 'InfusaLine 400', id: 'IL4', count: 150, firmware: ['3.8.4', '4.0.1', '4.1.0'], hours: [5.6, 0.55] },
  { model: 'InfusaLine 700', id: 'IL7', count: 90, firmware: ['4.0.1', '4.1.0'], hours: [5.9, 0.5] },
  { model: 'CardioTrack M5', id: 'CT5', count: 80, firmware: ['2.4.7', '2.5.0'], hours: [6.6, 0.4] },
  { model: 'Aeris V3', id: 'AV3', count: 45, firmware: ['1.9.2', '2.0.0'], hours: [5.2, 0.7] },
  { model: 'RenalPure D2', id: 'RP2', count: 35, firmware: ['5.1.3'], hours: [6.2, 0.45] },
];

const devices = [];

for (const spec of MODELS) {
  for (let i = 1; i <= spec.count; i++) {
    const firmware = pick(spec.firmware);
    const [mu, sigma] = spec.hours;
    const operating_hours = Math.round(clamp(Math.exp(mu + randn() * sigma), 20, 2400));

    // Latent health, 0 = perfect, 1 = falling apart. Nothing observes this
    // directly. downtime is driven by it, risk_score is a noisy read of it, and
    // the gap between those two is where the interesting question lives.
    let health = clamp(0.32 + randn() * 0.2, 0.01, 0.99);
    if (spec.firmware.length > 1 && firmware === spec.firmware[0]) health = clamp(health + 0.12, 0.01, 0.99);
    if (rand() < 0.03) health = clamp(health + 0.35, 0.01, 0.99); // the occasional lemon

    // Unplanned downtime, in minutes, scaled by how much the device ran.
    // Healthier devices often post a clean window and record nothing at all.
    const clean = rand() < 0.55 * (1 - health);
    const perHundred = 45 * health ** 2 * Math.exp(randn() * 0.5);
    const downtime_min = clean ? 0 : Math.round((perHundred * operating_hours) / 100);

    // Alerts fire on usage as well as ill health, so a busy healthy device can
    // out-alert a sick idle one. That is what makes the raw count misleading.
    const alerts = Math.max(0, Math.round(((0.8 + 9 * health) * operating_hours) / 100 + randn() * 2));

    // The vendor's advance risk call. It sees health through noise, which is
    // the whole reason it can be wrong about a specific device.
    const risk_score = Math.round(clamp(100 * health + randn() * 13, 1, 99));

    devices.push({
      device_id: `${spec.id}-${String(i).padStart(3, '0')}`,
      model: spec.model,
      site: pick(SITES),
      firmware,
      operating_hours,
      alerts,
      risk_score,
      downtime_min,
    });
  }
}

const fleet = {
  fleet: 'Regional network connected-device telemetry, 30-day window ending 2026-07-31',
  source: 'Synthetic. Generated by scripts/generate-fleet.mjs, seed ' + SEED + '. Not real patient or device data.',
  devices,
};

await writeFile(join(ROOT, 'data/fleet.json'), JSON.stringify(fleet, null, 2) + '\n', 'utf8');

console.log('wrote data/fleet.json');
console.log(`  devices: ${devices.length}`);
console.log(`  sites:   ${new Set(devices.map((d) => d.site)).size}`);
console.log(`  by model: ${JSON.stringify(
  devices.reduce((a, d) => ({ ...a, [d.model]: (a[d.model] ?? 0) + 1 }), {}),
)}`);
